
CREATE TABLE ROOT.GROUPS 
(
	GROUPID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	GROUPADMINID INTEGER NOT NULL,
	GROUPNAME VARCHAR(256) NOT NULL,
        GROUPISPRIVATE BOOLEAN NOT NULL DEFAULT TRUE,
        GROUPISOPEN BOOLEAN NOT NULL DEFAULT FALSE,
	GROUPDATACREATION DATE NOT NULL,
		PRIMARY KEY (GROUPID)
);

CREATE TABLE ROOT.GROUPUSER
(
	GROUPID INTEGER NOT NULL,
	USERID INTEGER NOT NULL,
	USERISADMIN BOOLEAN DEFAULT FALSE NOT NULL,
		PRIMARY KEY (GROUPID, USERID)
);

CREATE TABLE ROOT.INVITATION
(
	GROUPID INTEGER NOT NULL,
	USERID INTEGER NOT NULL,
		PRIMARY KEY (GROUPID, USERID)
);

CREATE TABLE ROOT.POST
(
	POSTID INTEGER NOT NULL,
	GROUPID INTEGER NOT NULL,
	USERID INTEGER NOT NULL,
	POSTDATACREATION TIMESTAMP NOT NULL,
	POSTTEXT CLOB,
		PRIMARY KEY (POSTID)
);

CREATE TABLE ROOT.POSTFILE
(
	POSTFILEID INTEGER NOT NULL,
        POSTID INTEGER NOT NULL,
	POSTFILEORIGINALFILENAME LONG VARCHAR,
	POSTFILEFILESYSTEMNAME LONG VARCHAR,
	POSTFILETYPE VARCHAR(1024),
		PRIMARY KEY (POSTFILEID)
);

CREATE TABLE ROOT.USERS
(
	USERID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USERNAME VARCHAR(256) UNIQUE NOT NULL,
	USERPWD VARCHAR(256) NOT NULL,
        USEREMAIL VARCHAR(256),  
	USERAVATAR LONG VARCHAR,
        USERMOD BOOLEAN NOT NULL DEFAULT FALSE,
        USERSITEADMIN BOOLEAN NOT NULL DEFAULT FALSE,
        USERLASTLOGIN TIMESTAMP,
            PRIMARY KEY (USERID)
);

ALTER TABLE ROOT.USERS ALTER COLUMN USERID RESTART WITH 1;
ALTER TABLE ROOT.GROUPS ALTER COLUMN GROUPID RESTART WITH 1;
